Extra Calculation Functions v1.2.4
Nottingham-CTU/Extra-Calculation-Functions pull request #8
Opened 2023-12-11 13:07 UTC by ninaclayton

added functionality so datalookup function works for checkbox fields.

2024-01-09 11:16 UTC, richdooley requested changes
Suggest amending the setting key.
Also as this adds a new option, version should perhaps be 1.3.0 rather than 1.2.4?

2024-01-09 11:47 UTC, ninaclayton commented on datalookup.php
> +		$lookupCheckboxSplit = $module->getProjectSetting( 'custom-data-lookup-split-checkbox_results' )[ $lookupIndex ];
updated as requested

2024-01-09 11:48 UTC, ninaclayton commented
> Suggest amending the setting key. Also as this adds a new option, version should perhaps be 1.3.0 rather than 1.2.4?

will release as v1.3

2024-01-15 08:37 UTC, richdooley approved these changes

2024-01-15 08:40 UTC, merged